config/routes.rb
Rails.application.routes.draw do
 
  
  devise_for :users
  
  
  root to: 'toppage#index'
  resource :timeline, only: [:show]

  get '/history', to: 'chat_histories#show'
  resource :history, only: [:show]


 resources :articles do
   resources :comments, only: [:index, :new, :show, :edit, :create, :update, :destroy]
   resource :like, only: [:show, :create, :destroy]

 end

 resources :accounts do
   resources :follows, only: [:create]
   resources :unfollows, only: [:create]
 end


 resources :chats do
   resources :replies, only: [:index, :new, :show, :edit, :create, :update, :destroy]
   resource :favorite, only: [:show, :create, :destroy]
 end
 
 resources :informations do
   resource :like, only: [:create, :destroy]
 end
 
 resources :lectures, only: [:index, :new, :show, :edit, :create, :update, :destroy]
 
 resources :favorites, only: [:index]
 resource :profile, only: [:show, :edit, :update]
 
 
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :eyecatch
  has_rich_text :content
  
  validates :title, presence: true
  validates :title, length: { minimum: 4, maximum: 100 }
  validates :title, format: { with: /\A(?!\@)/ }

  # validates :content, presence: true
  # validates :content, length: { minimum: 10 }, presence: true
  # validates :content, uniqueness: true
  # validate :validate_title_and_content_length
  
  has_many_attached :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user


  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def author_name
    user.display_name
  end

  def like_count
    likes.count
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end


  # private
  # def validate_title_and_content_length
  #   char_count = self.title.length + self.content.length
  #   errors.add(:content, '10文字以上必要です')unless char_count > 10
  # end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  

    before_action :set_article, only: [:show]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
      def index
        @articles = Article.all
  
      end
  
  
      def show
        @comment = @article.comments
        @user = @article.user 
      end
  
      
      def new
        @article = current_user.articles.build
  
      end
  
  
      def create
        @article = current_user.articles.build(article_params)
        
        if @article.save
          @article.images.attach(params[:article][:images])
          redirect_to article_path(@article), notice: '保存ができたよ'
        else
          flash.now[:error] = '保存に失敗しました'
          render :new
        end
      end
  
  
      def edit
        @article = current_user.articles.find(params[:id])
        @user = @article.user 
      end
  
  
      def update
        @article = current_user.articles.find(params[:id])
        
        if @article.update(article_params)
          redirect_to article_path(@article),notice: '更新できました'
        else
          flash.now[:error] = '更新できませんでした'
          render :edit
        end
  
      end
  
      def destroy
        article = current_user.articles.find(params[:id])
        article.destroy!
        redirect_to articles_path(@article), notice: '削除に成功しました'
  
      end
  
      private
      def article_params
        params.require(:article).permit(:title, :content, :eyecatch, images: [])
      end
  
      def set_article
        @article = Article.find(params[:id])
      end
  
  end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
.article_container
  %ul
    - @article.errors.full_messages.each do |message|
      %li= message
  = form_with(model: article, local: true) do |f|
    %div 
      = f.label :eyecatch, 'アイキャッチ画像'
    %div 
      = f.file_field :eyecatch 
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '本文'
    %div
      = f.rich_text_area :content
    %div
      = f.file_field :images, multiple: true, id: 'tweet_image', class: 'tweet-image-upload'
        
    
    = f.submit '保存', class: 'btn-primary'

app/views/articles/edit.html.haml
= render 'form', article: @article

app/views/articles/index.html.haml
.articles 
  .articles_container
    .index_container
      %h2 記事一覧
    .tabs
      = render 'commons/tabs'

    .new_article_container
      = link_to new_article_path do
        .article_new
          %p + 新しい記事を作成
    .wrap
      - @articles.order(created_at: :desc).each do |article|
        = render 'commons/article', article: article 

 

= link_to new_article_path do
  .float_btn
    %i.fa.fa-pencil

app/views/articles/new.html.haml
.index_container
  %h2 新しい記事を書こう!
= render 'form', article: @article

app/views/articles/show.html.haml
.index_container
  %h2 記事詳細ページ
.article#article-show{data: {article_id: @article.id}}
  - if @article.eyecatch.attached?
    .article_image
      = image_tag @article.eyecatch
  - else
    .card_image
      = image_tag 'default-eyecatch.jpg', size: '100*100'

  .article_detail
    = link_to account_path(@article.user) do
      = image_tag @article.user.avatar_image
    %div
      %p= @article.author_name
      %p= @article.display_created_at
    - if user_signed_in? && current_user.has_written?(@article)
      .article_detail_actions
        .dropdown
          = image_tag 'actions.svg', class: 'dropbtn'
          .dropdown-content.mini
            = link_to '編集する', edit_article_path(@article)
            = link_to '削除する', article_path(@article), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
    
    - elsif user_signed_in?   
      .article_follow_button
        - if current_user&.has_followed?(@user)
          = link_to 'フォロー済み', account_unfollows_path(@user), data: {method: 'post'}
        - else 
          = link_to 'フォローする', account_follows_path(@user), data: {method: 'post'}

  -# %p title:
  %h1.article_title= @article.title
  .article_content
    -# %p content:
    %p=h @article.content.body
    - if @article.images.attached?
      - @article.images.each do |image|
        = image_tag image
 


  .article_reactions
    - if user_signed_in?
      .article_heart.hidden.active-heart
        = image_tag 'heart-active.svg'  
      .article_heart.hidden.inactive-heart
        = image_tag 'heart.svg'
    
      .article_heart_count 
        = @article.like_count
       

  
.article 
  %h2 コメント一覧
  .comments-container  
    - @comment.each do |comment|
      = link_to account_path(comment.user) do
        .article_comment
          = image_tag comment.user.avatar_image
          %p= comment.content

.comment_container
  .btn-secondary.show-comment-form
    コメントを追加

  .comment-text-area.hidden
    
    = text_area_tag :comment_content, '', class: 'sm'
    .btn-secondary.add-comment-button
      コメントを追加

= javascript_pack_tag 'article' 