config/routes.rb
Rails.application.routes.draw do
 
  
  devise_for :users
  
  
  root to: 'toppage#index'
  resource :timeline, only: [:show]

  get '/history', to: 'chat_histories#show'
  resource :history, only: [:show]


 resources :articles do
   resources :comments, only: [:index, :new, :show, :edit, :create, :update, :destroy]
   resource :like, only: [:show, :create, :destroy]

 end

 resources :accounts do
   resources :follows, only: [:create]
   resources :unfollows, only: [:create]
 end


 resources :chats do
   resources :replies, only: [:index, :new, :show, :edit, :create, :update, :destroy]
   resource :favorite, only: [:show, :create, :destroy]
 end
 
 resources :informations do
   resource :like, only: [:create, :destroy]
 end
 
 resources :lectures, only: [:index, :new, :show, :edit, :create, :update, :destroy]
 
 resources :favorites, only: [:index]
 resource :profile, only: [:show, :edit, :update]
 
 
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :eyecatch
  has_rich_text :content
  
  validates :title, presence: true
  validates :title, length: { minimum: 4, maximum: 100 }
  validates :title, format: { with: /\A(?!\@)/ }

  # validates :content, presence: true
  # validates :content, length: { minimum: 10 }, presence: true
  # validates :content, uniqueness: true
  # validate :validate_title_and_content_length
  
  has_many_attached :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user


  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def author_name
    user.display_name
  end

  def like_count
    likes.count
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end


  # private
  # def validate_title_and_content_length
  #   char_count = self.title.length + self.content.length
  #   errors.add(:content, '10文字以上必要です')unless char_count > 10
  # end


end

app/models/chat.rb
class Chat < ApplicationRecord
  
  belongs_to :user
  has_many :replies
  has_many :favorites, dependent: :destroy
  has_rich_text :content

  # validates :content, length: { minimum: 3 }


  # validates :content, presence: true
  # validates :content, uniqueness: true
  validates :content, length: { maximum: 300 }, presence: true

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def author_name
    user.display_name
  end

  def favorite_count
    favorites.count
  end

  # def truncated_content(rich_text)
  #   truncate(rich_text.to_plain_text, length: 10, separator: "...")
  # end




end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  has_one_attached :avatar
  validates :content, presence: true
 

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :chat
  end
  

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
    has_one_attached :avatar

    def avatar_image
      if profile&.avatar&.attached?
        profile.avatar
      else
        'default-avatar.png'
      end
    end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
end

app/models/reply.rb
class Reply < ApplicationRecord
    belongs_to :chat
    belongs_to :user
    has_one_attached :avatar
    validates :content, presence: true
      
    def avatar_image
      if profile&.avatar&.attached?
         profile.avatar
      else
         'default-avatar.png'
      end
    end
  
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :likes,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :replies, dependent: :destroy
  # has_many :informations, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  has_many_attached :images
  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followings, through: :following_relationships, source: :following

  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower

  include Rails.application.routes.url_helpers

  # def avatar_url
  #   if avatar.attached?
  #     rails_blob_path(avatar, only_path: true)
  #   else
  #     '../default-avatar.png' # デフォルトのアバター画像のパスを指定
  #   end
  # end

  def has_written?(article)
    articles.exists?(id: article.id)
  end

  def has_written2?(information)
    informations.exists?(id: information.id)
  end

  def has_written3?(chat)
    chats.exists?(id: chat.id)
  end

  def has_liked?(article)
    likes.exists?(article_id: article.id)
  end

  def has_favorited?(chat)
    favorites.exists?(chat_id: chat.id)
  end

  def display_name
    profile&.nickname.presence || self.email.split('@').first
  end

  def follow!(user)
    # if user.is_a?(User)
    #   user_id = user.id
    # else
    #   user_id = user
    # end  
    user_id = get_user_id(user)
    following_relationships.create!(following_id: user_id)
  end

  def unfollow!(user)
    # if user.is_a?(User)
    #   user_id = user.id
    # else
    #   user_id = user
    # end  
    user_id = get_user_id(user)
    relation = following_relationships.find_by(following_id: user_id)
    relation.destroy!
  end

  def has_followed?(user)
    following_relationships.exists?(following_id: user.id)
  end



  def prepare_profile
    profile || build_profile
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end
  
private
  def get_user_id(user)
    if user.is_a?(User)
      # user_id = user.id
      user.id
    else
      # user_id = user
      user
    end  
  end  

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
    before_action :set_chat, only: [:show]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    
    
    def index
      @chats = Chat.all
 
    end
  
  
    def show
     @reply = @chat.replies
     @user = @chat.user 
    end
  
  
    def new
      @chat = current_user.chats.build
  
    end
  
  
    def create
      @chat = current_user.chats.build(chat_params)
      if @chat.save
        redirect_to chats_path(@chat), notice: "チャットを作成しました"
      else
        flash.now[:alert] = 'チャットの投稿に失敗しました'
        render new_chat_path
      end
    end
  
  
    def edit
      @chat = current_user.chats.find(params[:id])
  
    end
  
  
    def update
      @chat = current_user.chats.find(params[:id])
      if @chat.update(chat_params)
        redirect_to chat_path(@chat),notice: '更新できました'
      else
        flash.now[:error] = '更新できませんでした'
        render :edit
      end
  
  
    end
  
 
    def destroy
      chat = current_user.chats.find(params[:id])
      chat.destroy!
      redirect_to chats_path(@chat), notice: '削除に成功しました'
  
    end
  
    private
 
    def chat_params
      params.require(:chat).permit(:content)
    end
   
    def set_chat
     @chat = Chat.find(params[:id])
   end
 
 end
 
 

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tabs_helper.rb
module TabsHelper
    def add_active_class(path)
      'active' if current_page?(path)
    end
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/helpers/unfollows_helper.rb
module UnfollowsHelper
end

app/views/chats/_form.html.haml
.container
  %ul
    - @chat.errors.full_messages.each do |message|
      %li= message
  = form_with(model: chat, local: true) do |f|
    %div
      = f.label :content, 'Description'
    %div.rich
      = f.rich_text_area :content
    
    = f.submit '保存', class: 'btn-primary'

app/views/chats/edit.html.haml
= render 'form', chat: @chat

app/views/chats/index.html.haml
.chats
  
  .chats_container
    .index_container
      %h2 chat一覧を表示
    .tabs
      = render 'commons/chat_tabs'

    .new_chat_container
      = link_to new_chat_path do
        .chat_new
          %p + 新しいチャットを作成
    
    .wrap
      - @chats.order(created_at: :desc).each do |chat|
        = render 'commons/chat', chat: chat 
  

= link_to new_chat_path do
  .float_btn
    %i.fa.fa-pencil

app/views/chats/new.html.haml
.index_container
  %h2 新チャットを立ててみよう！
= render 'form', chat: @chat

app/views/chats/show.html.haml
.index_container
  %h2 チャット詳細ページ
.chat#chat-show{data: {chat_id: @chat.id}}
  .chat_container
    .chat_detail
      = link_to account_path(@chat.user) do
        = image_tag @chat.user.avatar_image
    %div
      %p= @chat.author_name
      %p= @chat.display_created_at
    - if user_signed_in? && current_user.has_written3?(@chat)
      .chat_detail_actions
        .dropdown
          = image_tag 'actions.svg', class: 'dropbtn'
          .dropdown-content.mini
            = link_to '編集する', edit_chat_path(@chat)
            = link_to '削除する', chat_path(@chat), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
    - elsif user_signed_in?  
      .chat_follow_button
        - if current_user&.has_followed?(@user)
          = link_to 'フォロー済み', account_unfollows_path(@user), data: {method: 'post'}
        - else 
          = link_to 'フォローする', account_follows_path(@user), data: {method: 'post'}
  
  .chat_content_container
    %p=h @chat.content
    .chat_reply_heart
      - if user_signed_in?
        .chat_heart.hidden.active-heart
          = image_tag 'heart-active.svg'  
        .chat_heart.hidden.inactive-heart
          = image_tag 'heart.svg'
        .chat_heart_count
          = @chat.favorite_count

    
.reply
  %h2 返信一覧
  .replies-container
    - @reply.each do |reply|
      = link_to account_path(reply.user) do
        .chat_reply
          = image_tag reply.user.avatar_image
          %p= reply.content

.reply_container
  .btn-secondary.show-reply-form
    返信を追加

  .reply-text-area.hidden
    = text_area_tag :reply_content, '', class: 'sm'
    
    .btn-secondary.add-reply-button
      返信を追加

= javascript_pack_tag 'chat' # JavaScriptファイル名がarticle.jsでなく、chat.jsであるため修正しました。