config/routes.rb
Rails.application.routes.draw do
 
  
  devise_for :users
  
  
  root to: 'toppage#index'
  resource :timeline, only: [:show]

  get '/history', to: 'chat_histories#show'
  resource :history, only: [:show]


 resources :articles do
   resources :comments, only: [:index, :new, :show, :edit, :create, :update, :destroy]
   resource :like, only: [:show, :create, :destroy]

 end

 resources :accounts do
   resources :follows, only: [:create]
   resources :unfollows, only: [:create]
 end


 resources :chats do
   resources :replies, only: [:index, :new, :show, :edit, :create, :update, :destroy]
   resource :favorite, only: [:show, :create, :destroy]
 end
 
 resources :informations do
   resource :like, only: [:create, :destroy]
 end
 
 resources :lectures, only: [:index, :new, :show, :edit, :create, :update, :destroy]
 
 resources :favorites, only: [:index]
 resource :profile, only: [:show, :edit, :update]
 
 
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :eyecatch
  has_rich_text :content
  
  validates :title, presence: true
  validates :title, length: { minimum: 4, maximum: 100 }
  validates :title, format: { with: /\A(?!\@)/ }

  # validates :content, presence: true
  # validates :content, length: { minimum: 10 }, presence: true
  # validates :content, uniqueness: true
  # validate :validate_title_and_content_length
  
  has_many_attached :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user


  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def author_name
    user.display_name
  end

  def like_count
    likes.count
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end


  # private
  # def validate_title_and_content_length
  #   char_count = self.title.length + self.content.length
  #   errors.add(:content, '10文字以上必要です')unless char_count > 10
  # end


end

app/models/chat.rb
class Chat < ApplicationRecord
  
  belongs_to :user
  has_many :replies
  has_many :favorites, dependent: :destroy
  has_rich_text :content

  # validates :content, length: { minimum: 3 }


  # validates :content, presence: true
  # validates :content, uniqueness: true
  validates :content, length: { maximum: 300 }, presence: true

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def author_name
    user.display_name
  end

  def favorite_count
    favorites.count
  end

  # def truncated_content(rich_text)
  #   truncate(rich_text.to_plain_text, length: 10, separator: "...")
  # end




end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  has_one_attached :avatar
  validates :content, presence: true
 

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :chat
  end
  

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
    has_one_attached :avatar

    def avatar_image
      if profile&.avatar&.attached?
        profile.avatar
      else
        'default-avatar.png'
      end
    end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
end

app/models/reply.rb
class Reply < ApplicationRecord
    belongs_to :chat
    belongs_to :user
    has_one_attached :avatar
    validates :content, presence: true
      
    def avatar_image
      if profile&.avatar&.attached?
         profile.avatar
      else
         'default-avatar.png'
      end
    end
  
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :likes,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :replies, dependent: :destroy
  # has_many :informations, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  has_many_attached :images
  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followings, through: :following_relationships, source: :following

  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower

  include Rails.application.routes.url_helpers

  # def avatar_url
  #   if avatar.attached?
  #     rails_blob_path(avatar, only_path: true)
  #   else
  #     '../default-avatar.png' # デフォルトのアバター画像のパスを指定
  #   end
  # end

  def has_written?(article)
    articles.exists?(id: article.id)
  end

  def has_written2?(information)
    informations.exists?(id: information.id)
  end

  def has_written3?(chat)
    chats.exists?(id: chat.id)
  end

  def has_liked?(article)
    likes.exists?(article_id: article.id)
  end

  def has_favorited?(chat)
    favorites.exists?(chat_id: chat.id)
  end

  def display_name
    profile&.nickname.presence || self.email.split('@').first
  end

  def follow!(user)
    # if user.is_a?(User)
    #   user_id = user.id
    # else
    #   user_id = user
    # end  
    user_id = get_user_id(user)
    following_relationships.create!(following_id: user_id)
  end

  def unfollow!(user)
    # if user.is_a?(User)
    #   user_id = user.id
    # else
    #   user_id = user
    # end  
    user_id = get_user_id(user)
    relation = following_relationships.find_by(following_id: user_id)
    relation.destroy!
  end

  def has_followed?(user)
    following_relationships.exists?(following_id: user.id)
  end



  def prepare_profile
    profile || build_profile
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end
  
private
  def get_user_id(user)
    if user.is_a?(User)
      # user_id = user.id
      user.id
    else
      # user_id = user
      user
    end  
  end  

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tabs_helper.rb
module TabsHelper
    def add_active_class(path)
      'active' if current_page?(path)
    end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/commons/_article.html.haml
.item
  = link_to article_path(article) do
    .card
      - if article.eyecatch.attached? 
        .card_image
          = image_tag article.eyecatch
      - else
        .card_image
          = image_tag 'default-eyecatch.jpg', size: '150*200'
      .card_content
        .card_title
          -# = article.title
          = truncate(article.title, length:12) 
          .card_articl_detail
            = image_tag article.user.avatar_image
            %div
              %p= article.author_name
              %p= article.display_created_at
        

app/views/commons/_chat.html.haml
.chat_item
  = link_to chat_path(chat) do
    .chat_card
      .card_detail
        .div
          = image_tag chat.user.avatar_image 
        .card_detail_text
          = truncate(chat.content.to_plain_text, length: 14, class: "truncate")
          .chat_display
            %div
              %p= chat.author_name
              %p= chat.display_created_at
        -# = truncate(chat.content, length:25) 
        -# =h chat.content

app/views/commons/_chat_tabs.html.haml
.tabs_item{class: "#{add_active_class(chats_path)}"}
  = link_to '新着チャット一覧', chats_path
  
.tabs_item{class: "#{add_active_class(history_path)}"}
  = link_to 'フォロータイムライン', history_path

app/views/commons/_information.html.haml
.item
  = link_to information_path(information) do
    .card
      - if information.eyecatch.attached? 
        .card_image
          = image_tag information.eyecatch
      - else
        .card_image
          = image_tag 'default-eyecatch.jpg', size: '150*200'
      .card_content
        .card_title
          = truncate(information.title, length:10) 

          .card_lecture_detail
            = image_tag information.user.avatar_image
            %div
              %p= information.author_name
              %p= information.display_created_at
          

app/views/commons/_profile.html.haml
.container_profilePage
  %h1 プロフィールページ
  .profilePage_user
    .profilePage_user_image
      = image_tag user.avatar_image
    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_displayName
          #{user.display_name}
        - if user_signed_in?  
          .profilePage_user_actionButton
            - if user == current_user
              = link_to 'Edit', edit_profile_path
            - elsif user_signed_in? 
              - if current_user&.has_followed?(user)
                = link_to 'フォロー済み', account_unfollows_path(user), data: {method: 'post'}
              - else 
                = link_to 'フォローする', account_follows_path(user), data: {method: 'post'}
      .profilePage_user_introduction
        = user.profile&.introduction
           
  -# - user.articles.each do |article| 
  -#   = render 'commons/article', article: article

.index_container
  %h2 記事一覧！
.wrap
  .profile_item
    - user.articles.order(created_at: :desc).each do |article|
      -# - user.articles.each do |article| 
      = link_to article_path(article) do
        .card
          - if article.eyecatch.attached? 
            .card_image
              = image_tag article.eyecatch
          - else
            .card_image
              = image_tag 'default-eyecatch.jpg'
          .card_content
            .card_title
              = article.title
              -# = truncate(article.title, length:13) 
              .profile_card_detail
                = image_tag article.user.avatar_image
                %div
                  %p= article.author_name
                  %p= article.display_created_at

.index_container
  %h2 チャット一覧
.wrap
  - user.chats.each do |chat| 
    = link_to chat_path(chat) do
      .chat_card
        .card_detail
          .div
            = image_tag chat.user.avatar_image 
          .card_detail_text
            = truncate(chat.content.to_plain_text, length: 14, class: "truncate")
            .chat_display
              %div
                %p= chat.author_name
                %p= chat.display_created_at
          -# = truncate(chat.content, length:25) 
          -# =h chat.content

.index_container
  %h2 インフォメーション
-# .wrap
-#   .profile_item
-#     - user.informations.each do |information| 
-#       = link_to information_path(information) do
-#         .card
-#           - if information.eyecatch.attached? 
-#             .card_image
-#               = image_tag information.eyecatch
-#           - else
-#             .card_image
-#               = image_tag 'default-eyecatch.jpg'
-#           .card_content
-#             .card_title
-#               = information.title

-#               .profile_card_detail
-#                 = image_tag information.user.avatar_image
-#                 %div
-#                   %p= information.author_name
-#                   %p= information.display_created_at

app/views/commons/_tabs.html.haml
.tabs_item{class: "#{add_active_class(articles_path)}"}
  = link_to '新着記事一覧', articles_path
  
.tabs_item{class: "#{add_active_class(timeline_path)}"}
  = link_to 'フォロータイムライン', timeline_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title 群馬MHSW 災害支援共有ボード
    %display_meta_tags(default_meta_tags) 
    %meta{ property: 'og:image', content: image_url('IMG_6345.PNG') }
    -# %meta "専門職"のための災害支援ツールですチャットで意見交換、記事で情報共有が行えます” 
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
   

    %header.header
      .header_logos
        .header_pagetitle
          .pagetitle
            = link_to '共有ボードtop', root_path
       
        - if user_signed_in?
          .dropdown
            = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
            .dropdown-content
              = link_to 'プロフィール', profile_path
              -# = link_to 'お気に入り', favorites_path
              = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }
        - else
          = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'
    
    .sitetitle 
      %h1 群馬MHSW<br>災害支援共有ボード

    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield
  
  .footerWrap
    .footer 
      %P コピーライト2022